### PR TITLE
Html form

### PR DESCRIPTION
**Pull request by ClintonEnyinna**

### CODE REVIEW

**Comment by Anna-Myzukina** [comment]
#### Pull Request under the review by Anna Muzykina (TSE)

**Comment by Anna-Myzukina** [comment]
#### Hi team!
#### Nice gob! Readme file descriptive! :+1: 

#### But need some Required Changes

##### Fix linter now it`s not working.

###### Bottom

* [ ] It should have a disclaimer text that matches the context and style of the original page ([link to page](https://accounts.intuit.com/signup.html))

original


##### Footer

* [ ] It should contains copyright and address information ([link to page](https://accounts.intuit.com/signup.html))

footer

Your version now without bottom and footer. Plese fix this.

main


Great that you use the [`<main>` tag](https://www.w3schools.com/tags/tag_main.asp) for the dominant content of the `<body>`  and the [`<footer>`](https://www.w3schools.com/TagS/tag_footer.asp) tag for the footer, but not bad to use of a  [`<nav>` tag](http://html5doctor.com/nav-element/) in HTML document too. Maybe in the next project, you can try.


### Make changes and submit another code review request.

*If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you.*
*Happy coding 😄*

**Review by Anna-Myzukina — CHANGES_REQUESTED** [review]
The project needs changes in the bottom and footer parts. Linter not working.

**Comment by ClintonEnyinna** [comment]
We had a footer, it was cut off because of overflow hidden in css. We've made necessary corrections

**Review by fatymahmed — CHANGES_REQUESTED** [review]
## Hi @ClintonEnyinna @moinkhanif,
Great job on making the changes suggested by the previous TSE, however there are still some things left to fix.

- As mentioned in the previous review, you should set up linter as it's not working. You can find more instructions on how to do so in [linters](https://github.com/microverseinc/linters-config/tree/master/css).
-As mention in pathwright (find screenshot below), you should use a html validator to check for any errors and fix them.
Screenshot from 2019-11-26 21-39-56
- As you can see on the screenshot attached below, your project has some errors, kindly fix these.
Screenshot from 2019-11-27 04-05-11
- Your inputs are not aligned the same way they are on the original page.
Screenshot from 2019-11-27 03-57-14

### Kindly fix these and request for another review.
## Status: Changes Required

**Review by imhta — APPROVED** [review]
# Project Approved 👍 

### Hello @ClintonEnyinna @moinkhanif , 👋 You have done great job with this project. 👏 



----
#### Don't forgot to sumbit project completion form
 **Pon Muthu Selvam N**
Feel free contact me 
[Github //@imhta](https://github.com/imhta) | [Twitter //@nponmuthuselvam](https://twitter.com/ponmuthuselvam)

**Pull request merged**
